"""
Rule application module.

Applies generated rules directly to Cursor settings (global or project-level).
"""

import os
import json
import platform
from pathlib import Path
from typing import Optional

from rich.console import Console
from rich.prompt import Confirm
from rich.panel import Panel

console = Console()


def get_cursor_settings_path() -> Optional[Path]:
    """
    Get the path to Cursor's global settings.json.
    
    Returns:
        Path to settings.json, or None if not found
    """
    system = platform.system()
    
    if system == "Darwin":  # macOS
        settings_path = Path.home() / "Library" / "Application Support" / "Cursor" / "User" / "settings.json"
    elif system == "Windows":
        settings_path = Path(os.environ.get("APPDATA", "")) / "Cursor" / "User" / "settings.json"
    elif system == "Linux":
        settings_path = Path.home() / ".config" / "Cursor" / "User" / "settings.json"
    else:
        return None
    
    return settings_path if settings_path.exists() else None


def get_project_rules_path() -> Path:
    """
    Get the path for project-level rules.
    
    Returns:
        Path to .cursor/rules/ directory in current working directory
    """
    return Path.cwd() / ".cursor" / "rules"


def apply_rules(rules_path: Path, global_rules: bool = False, project_rules: bool = True):
    """
    Apply rules to Cursor settings.
    
    Args:
        rules_path: Path to the rules file to apply
        global_rules: If True, apply to global Cursor settings
        project_rules: If True, apply to project .cursor/rules/
    """
    # Read rules content
    with open(rules_path, 'r', encoding='utf-8') as f:
        rules_content = f.read()
    
    if global_rules:
        _apply_global_rules(rules_content)
    
    if project_rules:
        _apply_project_rules(rules_content)


def _apply_global_rules(rules_content: str):
    """Apply rules to global Cursor settings."""
    settings_path = get_cursor_settings_path()
    
    if not settings_path:
        console.print("[red]✗[/red] Could not find Cursor settings.json")
        console.print("[dim]Make sure Cursor is installed.[/dim]")
        return
    
    # Show preview
    console.print()
    console.print(Panel(
        rules_content[:400] + ("..." if len(rules_content) > 400 else ""),
        title="[bold]Rules to Apply[/bold]",
        border_style="cyan",
    ))
    console.print()
    console.print(f"[bold]Target:[/bold] {settings_path}")
    console.print()
    
    # Confirm
    if not Confirm.ask("Apply these rules to global Cursor settings?"):
        console.print("[yellow]Cancelled.[/yellow]")
        return
    
    # Read existing settings
    try:
        with open(settings_path, 'r', encoding='utf-8') as f:
            settings = json.load(f)
    except (json.JSONDecodeError, FileNotFoundError):
        settings = {}
    
    # Get existing rules
    existing_rules = settings.get("cursor.general.aiRules", "")
    
    # Merge rules (append new rules)
    if existing_rules:
        # Check if our rules are already there
        if "Generated by cursorhabits" in existing_rules:
            console.print("[yellow]⚠[/yellow] cursorhabits rules already present. Replacing...")
            # Remove old cursorhabits section
            import re
            existing_rules = re.sub(
                r'# Cursor Rules\n# Generated by cursorhabits.*?(?=\n# |$)',
                '',
                existing_rules,
                flags=re.DOTALL
            ).strip()
        
        merged_rules = existing_rules + "\n\n" + rules_content
    else:
        merged_rules = rules_content
    
    # Update settings
    settings["cursor.general.aiRules"] = merged_rules
    
    # Write back
    try:
        with open(settings_path, 'w', encoding='utf-8') as f:
            json.dump(settings, f, indent=2, ensure_ascii=False)
        
        console.print("[green]✓[/green] Rules applied to global Cursor settings")
        console.print("[dim]Restart Cursor to apply changes.[/dim]")
    except Exception as e:
        console.print(f"[red]✗[/red] Failed to write settings: {e}")


def _apply_project_rules(rules_content: str):
    """Apply rules to project .cursor/rules/ directory."""
    rules_dir = get_project_rules_path()
    rules_file = rules_dir / "habits.mdc"
    
    # Show preview
    console.print()
    console.print(Panel(
        rules_content[:400] + ("..." if len(rules_content) > 400 else ""),
        title="[bold]Rules to Apply[/bold]",
        border_style="cyan",
    ))
    console.print()
    console.print(f"[bold]Target:[/bold] {rules_file}")
    console.print()
    
    # Confirm
    if not Confirm.ask("Create/update project rules file?"):
        console.print("[yellow]Cancelled.[/yellow]")
        return
    
    # Create directory if needed
    rules_dir.mkdir(parents=True, exist_ok=True)
    
    # Format as .mdc file
    mdc_content = f"""---
description: Personal habits and preferences extracted from chat history
globs: 
alwaysApply: true
---

{rules_content}
"""
    
    # Check if file exists
    if rules_file.exists():
        console.print("[yellow]⚠[/yellow] habits.mdc already exists. Overwriting...")
    
    # Write file
    try:
        with open(rules_file, 'w', encoding='utf-8') as f:
            f.write(mdc_content)
        
        console.print(f"[green]✓[/green] Rules saved to {rules_file}")
        console.print("[dim]These rules will apply to all files in this project.[/dim]")
    except Exception as e:
        console.print(f"[red]✗[/red] Failed to write rules file: {e}")


def show_rules_locations():
    """Display where Cursor looks for rules."""
    console.print()
    console.print("[bold]Cursor Rules Locations:[/bold]")
    console.print()
    
    # Global
    global_path = get_cursor_settings_path()
    if global_path:
        console.print(f"  [cyan]Global:[/cyan] {global_path}")
        console.print("    [dim]Settings → cursor.general.aiRules[/dim]")
    else:
        console.print("  [cyan]Global:[/cyan] [dim]Not found[/dim]")
    
    console.print()
    
    # Project
    project_path = get_project_rules_path()
    console.print(f"  [cyan]Project:[/cyan] {project_path}/")
    console.print("    [dim].mdc files with alwaysApply: true[/dim]")
    
    console.print()

