"""
Output formatting module.

Provides beautiful terminal output using the Rich library.
"""

from pathlib import Path
from datetime import datetime

from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.text import Text
from rich import box

from .filters import clean_text

console = Console()


def print_results(patterns: dict, phrases: list, use_llm: bool = False):
    """
    Print analysis results in a beautiful format.
    
    Args:
        patterns: Dictionary of detected patterns
        phrases: List of (phrase, count) tuples
        use_llm: Whether LLM synthesis was used
    """
    console.print()
    
    if not patterns:
        console.print("[yellow]No clear patterns detected.[/yellow]")
        console.print("[dim]Try running with more chat history or fewer days filter.[/dim]")
        return
    
    # Patterns section
    console.print("[bold]Detected Patterns[/bold]")
    console.print()
    
    for i, (name, data) in enumerate(list(patterns.items())[:8], 1):
        label = data.get('label', name.replace('_', ' ').title())
        count = data['count']
        examples = data.get('examples', [])
        
        # Pattern header
        console.print(f"  [cyan][{i}][/cyan] [bold]{label}[/bold] [dim]({count} mentions)[/dim]")
        
        # Show top example
        if examples:
            example = clean_text(examples[0])
            if len(example) > 80:
                example = example[:77] + "..."
            console.print(f"      [dim]\"{example}\"[/dim]")
        
        console.print()
    
    # Repeated phrases section (if any)
    if phrases:
        console.print("[bold]Repeated Phrases[/bold]")
        console.print()
        
        for phrase, count in phrases[:5]:
            console.print(f"  [dim]({count}x)[/dim] \"{phrase}\"")
        
        console.print()
    
    # Synthesis indicator
    if use_llm:
        console.print("[green]✓[/green] Rules synthesized with AI for better readability")
    else:
        console.print("[dim]Tip: Run without --no-llm for AI-enhanced rules[/dim]")


def save_rules(content: str, output_path: Path):
    """
    Save generated rules to a file.
    
    Args:
        content: Rules content (markdown)
        output_path: Path to save the file
    """
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)


def format_rules_basic(patterns: dict, phrases: list) -> str:
    """
    Format rules in basic markdown (no LLM).
    
    Args:
        patterns: Dictionary of detected patterns
        phrases: List of (phrase, count) tuples
        
    Returns:
        Markdown-formatted rules string
    """
    lines = [
        "# Suggested Cursor Rules",
        f"# Generated by cursorhabits on {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
    ]
    
    # Group patterns by category
    categories = {}
    for name, data in patterns.items():
        label = data.get('label', name.replace('_', ' ').title())
        if label not in categories:
            categories[label] = []
        categories[label].append(data)
    
    for category, items in categories.items():
        total_count = sum(item['count'] for item in items)
        lines.append(f"## {category} ({total_count} mentions)")
        lines.append("")
        
        for item in items:
            examples = item.get('examples', [])
            if examples:
                # Use the first example as a rule suggestion
                example = clean_text(examples[0])
                if len(example) > 100:
                    example = example[:97] + "..."
                lines.append(f"- {example}")
        
        lines.append("")
    
    # Repeated phrases
    if phrases:
        lines.append("## Frequently Repeated")
        lines.append("")
        for phrase, count in phrases[:10]:
            lines.append(f"- ({count}x) \"{phrase}\"")
        lines.append("")
    
    return '\n'.join(lines)


def print_apply_preview(rules_content: str, target: str):
    """
    Print a preview of rules being applied.
    
    Args:
        rules_content: The rules content to apply
        target: Description of where rules will be applied
    """
    console.print()
    console.print(Panel(
        rules_content[:500] + ("..." if len(rules_content) > 500 else ""),
        title="[bold]Rules Preview[/bold]",
        border_style="cyan",
        padding=(1, 2),
    ))
    console.print()
    console.print(f"[bold]Target:[/bold] {target}")
    console.print()


def print_success(message: str):
    """Print a success message."""
    console.print(f"[green]✓[/green] {message}")


def print_error(message: str):
    """Print an error message."""
    console.print(f"[red]✗[/red] {message}")


def print_warning(message: str):
    """Print a warning message."""
    console.print(f"[yellow]⚠[/yellow] {message}")

